# Generated by Django 3.1.1 on 2020-10-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201030_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(default='Free', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership'),
        ),
    ]
