# Generated by Django 3.1.1 on 2020-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='voteValue',
            field=models.CharField(choices=[('none', 'none'), ('like', 'like'), ('dislike', 'dislike')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='videovote',
            name='voteValue',
            field=models.CharField(choices=[('none', 'none'), ('like', 'like'), ('dislike', 'dislike')], default='none', max_length=10),
        ),
    ]
