# Generated by Django 3.1.1 on 2020-10-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20201020_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reported', 'Reported'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reported', 'Reported'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
