# Generated by Django 3.1.1 on 2020-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='image',
            field=models.ImageField(null=True, upload_to='categoryImg/'),
        ),
    ]
