# Generated by Django 3.1.1 on 2020-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20201021_0517'),
        ('video', '0003_auto_20201021_0526'),
    ]

    operations = [
    ]
