# Generated by Django 3.1.1 on 2020-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('video', '0003_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allowed_membership',
            field=models.ManyToManyField(to='membership.Membership'),
        ),
    ]
