# Generated by Django 3.1.1 on 2020-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videocategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
    ]
