# Generated by Django 3.1.1 on 2020-10-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_allowed_membership'),
        ('video', '0005_videocategory_image'),
    ]

    operations = [
    ]
